cluster:
  name: "banzai-cicd-cluster"
  provider: "google"

workspace:
  base: /go
  path: src/github.com/banzaicloud/pipeline

pipeline:
  print_env:
    image: golang:1.10
    commands:
    - pwd
    - env
    - find .
    - sleep 1
    group: build

  build:
    image: golang:1.10
    commands:
    - make build

  test:
    image: golang:1.10
    commands:
    - mkdir $HOME/config
    - cp config/config.toml.example $HOME/config/config.toml
    - make test
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf

  build_container:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: banzaicloud/pipeline
    tags: {{ printf "cicd-%s" (.DRONE_COMMIT_SHA | trunc 7) }}
    log: debug

services:
  vault:
    image: vault:0.10.3
    ports:
    - 8200
    environment:
      SKIP_SETCAP: "true"
      VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
  